spring:
  #Data Base
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:~/website
    username: sa
    password:
  #JPA
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    com.website.didado.domain.board: debug
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace
---
spring:
  config:
    activate:
      on-profile: dev
  #JPA
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:/websitev
#    username: sa
#    password:
server:
  port: 8081
---
spring:
  config:
    activate:
      on-profile: prod
  #JPA
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    com.website.didado.domain.board: info
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace