spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  datasource:
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.h2.Driver}
    url: ${SPRING_DATASOURCE_URL:jdbc:h2:mem:/website}
    username: ${SPRING_DATASOURCE_USERNAME:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    com.didado.content: debug
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace

server:
  port: 8083

lostark:
  url: "${LOSTARK_URL}"
  api:
    key: "${LOSTARK_API_KEY}"
---
spring:
  config:
    activate:
      on-profile: dev
  #JPA
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: false

#lostark:
#  url: "file:+${LOSTARK_URL}"
#  api:
#    key: "file:${LOSTARK_API_KEY}"
---
spring:
  config:
    activate:
      on-profile: prod
  #JPA
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: false

logging:
  level:
    com.didado.content: info
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace