services:
  didado-website:
    container_name: didado-website-dev
    image: didado-website
    ports:
      - "8081:8081"
    networks:
      - didado-dev-net
    environment:
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/website
      SPRING_DATASOURCE_USERNAME: website
      SPRING_DATASOURCE_PASSWORD: website
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      - database
  database:
    container_name: database-dev
    image: postgres:latest
    ports:
      - "5432:5432"
    networks:
      - didado-dev-net
    environment:
      POSTGRES_DB: website
      POSTGRES_USER: website
      POSTGRES_PASSWORD: website
    volumes:
      - /Users/didado/desktop/database/dev:/var/lib/postgresql/data
networks:
  didado-dev-net:
    external: true