spring:
  #Data Base
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  datasource:
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.h2.Driver}
    url: ${SPRING_DATASOURCE_URL:jdbc:h2:mem:/website}
    username: ${SPRING_DATASOURCE_USERNAME:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:}
  #JPA
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
      hibernate.default_batch_fetch_size: 1000

logging:
  level:
    com.didado.armory.domain: debug
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace

server:
  port: 8080

lostark:
  url: "${LOSTARK_URL}"
  api:
    key: "${LOSTARK_API_KEY}"

---
spring:
  config:
    activate:
      on-profile: dev
  #JPA
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: false

  h2:
    console:
      enabled: false
---
spring:
  config:
    activate:
      on-profile: prod
  #JPA
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: false
  h2:
    console:
      enabled: false
logging:
  level:
    com.didado.armory.domain: info
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace